# SPDX-FileCopyrightText: 2023 ash_double_entry contributors <https://github.com/ash-project/ash_double_entry/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshDoubleEntry.Test.Repo.Migrations.DeleteBalances do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop(constraint(:balances, "balances_transfer_id_fkey"))

    alter table(:balances) do
      modify(
        :transfer_id,
        references(:transfers,
          column: :id,
          name: "balances_transfer_id_fkey",
          type: :binary,
          on_delete: :delete_all
        )
      )
    end
  end

  def down do
    drop(constraint(:balances, "balances_transfer_id_fkey"))

    alter table(:balances) do
      modify(
        :transfer_id,
        references(:transfers, column: :id, name: "balances_transfer_id_fkey", type: :binary)
      )
    end
  end
end
